"""create table movies

Revision ID: 4241ef38d9ca
Revises: 
Create Date: 2025-09-19 09:54:45.916721

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
import sqlmodel

import python_pg_bigm


# revision identifiers, used by Alembic.
revision: str = '4241ef38d9ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', python_pg_bigm.entity.movie.Vector(384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movies_embedding_ivf', 'movies', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.create_index('idx_movies_title_gin', 'movies', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_title_gin', table_name='movies', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_movies_embedding_ivf', table_name='movies', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.drop_table('movies')
    # ### end Alembic commands ###
